package graph;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;

/**
 * Stores graph information
 */
public class DataModel {

    /**
     * name of x-axis
     */
    private String xAxisName;

    /**
     * name of y-axis
     */
    private String yAxisName;

    /**
     * HashMap of trial data
     */
    private HashMap<Integer, ArrayList<Trial>> trialMap;

    /**
     * Import data from file and fill in model
     *
     * @param path path to file
     */
    public DataModel(String path) {
        parseCSV(path);
    }

    /**
     * returns trial data
     *
     * @return trial data
     */
    public HashMap<Integer, ArrayList<Trial>> getData() {
        return trialMap;
    }

    /**
     * returns x-axis name
     *
     * @return x-axis name
     */
    public String getxAxisName() {
        return xAxisName;
    }

    /**
     * returns x-axis name
     *
     * @return x-axis name
     */
    public String getyAxisName() {
        return yAxisName;
    }

    /**
     * Parses trial data CSV file generated by TestRecursionLimit
     *
     * @param path path to file
     */
    private void parseCSV(String path) {
        trialMap = new HashMap<>();
        try {
            Scanner scanner = new Scanner(new File(path));
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] words = line.split(",");
                if (line.startsWith("array")) {
                    xAxisName = words[1];
                    yAxisName = words[2];
                } else if (!line.isEmpty()) {
                    int index = Integer.parseInt(words[0]);
                    ArrayList<Trial> trials = trialMap.containsKey(index) ? trialMap.get(index) : new ArrayList<>();
                    trials.add(new Trial(Integer.parseInt(words[1]), Long.parseLong(words[2])));
                    trialMap.put(index, trials);
                }
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found. Please try again.");
            System.exit(0);
        }
    }
}